### ISSUE TITLE
Configure Homebridge Sonos Announcer

### ISSUE THREAD

**Issue by srenvoise** [jak/homebridge-sonos-announcer#4]
Hi,
I try to use the Homebridge Sonos Announcer plugin on Homebridge, and I can't configure it properly.

How do I find the exact name of my Sonos to enter it in the settings? (Name of the Sonos device (must be exact)
How to correctly configure URL to audio file?

Device name : "Chambre Matteo" like Sonos apps
URL to audio file: https://filesamples.com/samples/audio/aac/sample4.aac
gold
https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en&q=There%27s%20someone%20at%20the%20door
like your example

It does not work...
Sonos starts but not on the right music

Thanks for your help

Sebastien

**Comment by bajosoto** [comment]
I have the same question. I'm using the same name I see in the "About My System" section in my Sonos App, but I keep running into 
```
Error: No players found
    at EventEmitter.<anonymous> (/var/lib/homebridge/node_modules/@jakspalding/homebridge-sonos-announcer/node_modules/@svrooij/sonos/lib/sonos-device-discovery.js:96:24)
    at Object.onceWrapper (node:events:631:28)
    at EventEmitter.emit (node:events:517:28)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/@jakspalding/homebridge-sonos-announcer/node_modules/@svrooij/sonos/lib/sonos-device-discovery.js:84:25)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```
